### ISSUE TITLE
Not able to run the video.py

### ISSUE THREAD

**Issue by arorasahil1234** [infr/falldetector-public#1]
Hi ,

I was looking through your code however i was not able to run the video.py file 
It says cv2.putText(self.frame, "Status: {}".format(detectStatus), (10, 20), cv2.FONT_HERSHEY_SIMPLEX, 0.8,(0, 140, 255),1)
	 		cv2.putText(self.frame, "FPS: {}".format(fps), (400, 20), cv2.FONT_HERSHEY_SIMPLEX, 0.8,(0, 140, 255),1)
**Self is not defined**
I converted the code to python 3 However I am not able to run the file.
Please help me for the same

**Comment by infr** [comment]
Did you try to run main.py? Running video.py alone will not do anything.

Current code supports only python 2.7.x. You could do a pr if you rewrote the code to support python 3. Then I can have a look.

**Comment by arorasahil1234** [comment]
Hi ,

I have attached pdf files ,Please change extension from PDF to .py
The code is in python 3.6(Latest).
Please let me know if you able to run it :) thanks for your help



[bs.PDF](https://github.com/infr/falldetector-public/files/1526136/bs.PDF)
[main.pdf](https://github.com/infr/falldetector-public/files/1526138/main.pdf)
[person.pdf](https://github.com/infr/falldetector-public/files/1526139/person.pdf)
[settings.pdf](https://github.com/infr/falldetector-public/files/1526141/settings.pdf)
[video.pdf](https://github.com/infr/falldetector-public/files/1526142/video.pdf)
[webservice.pdf](https://github.com/infr/falldetector-public/files/1526143/webservice.pdf)







ll attached files in GitHub) However it is not working :(

**Comment by infr** [comment]
Please do a pull request with the new code. Here is how: https://help.github.com/articles/creating-a-pull-request-from-a-fork/

**Comment by arorasahil1234** [comment]
I am not able to find or how to do that.

 I tried running in 2.7.13 as well however I got a message Nonetype object has no attribute 'shape' (line 125)
I am new to python so apologies for inconvenience.

**Comment by NightyCloud** [comment]
Hi @arorasahil1234, encountered the same error of **AttributeError: 'NoneType' object has no attribute 'shape'**. Have you solved it? Thank you.
