### ISSUE TITLE
Not able to run

### ISSUE THREAD

**Issue by arorasahil1234** [infr/falldetector-public#2]
Hi ,

Sorry to bother you again ,I installed python 2.17.13
and tried to run the code however i am facing the below error could you please help me for the same
C:\Users\sahil.d.arora\Desktop\sw\falldetector-public-master\fall-detector-v2\video.py", line 137, in compare
    (contours, _) = cv2.findContours(self.thresh.copy(), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE) #find contours
ValueError: too many values to unpack

**Comment by waikit0624** [comment]
Greetings
I'm using python 2.7.14 and have the same error above when running main.py .
Any feedback is appreciated. Thanks

**Comment by infr** [comment]
@arorasahil1234 @waikit0624 I do not currently have a setup where I could run. I think findContours is returning 3 values, could you try modifying the line like this:
` _, contours, _ = cv2.findContours(self.thresh.copy(), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE) #find contours`

**Comment by waikit0624** [comment]
Traceback (most recent call last):
  File "C:\Users\lemon\OneDrive\Desktop\source code1\falldetector-public-master\fall-detector-v2\main.py", line 6, in <module>
    import video
  File "C:\Users\lemon\OneDrive\Desktop\source code1\falldetector-public-master\fall-detector-v2\video.py", line 13, in <module>
    import webservice
  File "C:\Users\lemon\OneDrive\Desktop\source code1\falldetector-public-master\fall-detector-v2\webservice.py", line 7, in <module>
    import requests
ImportError: No module named requests

Now i got to this ^ .. Thank you for ur response tho

**Comment by infr** [comment]
@waikit0624 now just run `pip install requests` and run the same pip install for other missing modules
